<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <!-- Build settings -->
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <!-- Application icon -->
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
